name: flutter_rays
description: 2D ray casting implemented in Flutter with CustomPaint and ValueListenableBuilder.
version: 2.0.0
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
